### ISSUE TITLE
[BUG] Not Working On Safari

### ISSUE THREAD

**Issue by Megrax** [Xav1erSue/Newjw_HDU_AutoChoose#1]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/56376387/145545920-6ab28cb1-0ccc-4e40-8b89-0c93f3e56da7.png">

- Safari Version :
```
版本15.1 (16612.2.9.1.30, 16612)
```
- TamperMonkey Version:
```
v4.13.6140 (latest for Safari)
```

**Comment by Xav1erSue** [comment]
it seems not working on Safari due to the Content-Security-Policy, and I have no idea about solving this.

**Comment by Megrax** [comment]
Looks fine.
![image](https://user-images.githubusercontent.com/56376387/145666667-78107b44-545f-48a0-8176-79d266942fb8.png)

- Safari Version :
```
版本14.0 (15610.1.28.1.9, 15610)
```
- TamperMonkey Version:
```
v4.13.6140 (latest for Safari)
```
- OS:
```
MacOS Catalina 0.15.7 (19H15)
```
